name: Update ZGHT1 Only

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # 每 6 小时自动运行一次

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Update ZGHT from iptvs.pes.im
      run: |
        node update_zght1.js

    - name: Commit ZGHT1
      run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      
          if git diff --quiet ZGHT1; then
            echo "No changes in ZGHT1"
          else
            git add ZGHT1
            git commit -m "Update ZGHT1 from iptvs.pes.im"
            git push
          fi
    - name: Cleanup commits older than 10 days
      run: |
        git fetch --all
    
        OLD_COMMIT=$(git rev-list -n 1 --before="10 days ago" main)
    
        if [ -z "$OLD_COMMIT" ]; then
          echo "No commits older than 10 days"
          exit 0
        fi
    
        git reset --soft $OLD_COMMIT
        git commit -m "Cleanup: keep commits from last 10 days"
        git push --force


