name: Update fwc.m3u

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download template
        run: |
          curl -L http://82.156.243.185:33389/fwc.m3u -o fwc.m3u
          curl -L http://izihao.cn:7123/ -o template.m3u

          # 直接把模板转换成 mg000（不会保留原始内容）
          sed -i "s/izihao.cn:7123/mg000/g" template.m3u
          
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto update m3u files"
          git push
